name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # First set up JDK 17 for Android SDK tools
    - name: Set up JDK 17 for Android tools
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK with JDK 17
      uses: android-actions/setup-android@v3
      with:
        packages: 'platforms;android-28 build-tools;28.0.3'
    
    # Then set up JDK 11 for actual building
    - name: Set up JDK 11 for building
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: |
        export ANDROID_HOME=/usr/local/lib/android/sdk
        export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$PATH
        export SKIP_JDK_VERSION_CHECK=1
        ./gradlew assembleDebug --info --stacktrace
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk